<div class="site_wrap">
        <div class="map_header_wrap">
            <div class="map_header cf">
                <div class="coi_logo">
                    <img src="../images/logo.png" alt="">
                </div>
                <div class="header_right cf">
                    <div class="header_login cf">
                        <p><span><a href="login.html">登录</a></span><span>|</span><span><a href="signin.html">注册</a></span>&nbsp;&nbsp;<span><a href="user_report.html">个人中心</a></span></p>

                    </div>
                    <div class="header_nav cf">
                        <ul>
                            <li><a class="nav_link" href="index.html">污染地图</a></li>
                            <li><a class="nav_link" href="report.html">分析报告</a></li>
                            <li><a class="nav_link" href="visual.html">可视化平台</a></li>
                            <li><a class="nav_link" href="price.html">价格</a></li>
                            <li><a class="nav_link" href="dataApi.html">数据API</a></li>
                        </ul>
                    </div>
                </div>
            </div>
        </div>

    </div>